from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_RAW_DIR = ROOT / "data" / "raw"
DATA_PROCESSED_DIR = ROOT / "data" / "processed"
PUBLIC_INPUT_DIR = ROOT / "data" / "public_inputs"
OUTPUT_DIR = ROOT / "output"
SCORECARD_OUTPUT_DIR = OUTPUT_DIR / "scorecard_outputs"

INDUSTRY_RISK_SOURCE_DIRS = (
    ROOT.parent / "9.Industry Risk Analysis_Australia",
    ROOT.parent / "industry_analysis",
)

RANDOM_SEED = 42
N_BORROWERS = 720
TEST_SIZE = 0.30
TARGET_DEFAULT_RATE = 0.11

BASE_SCORE = 600.0
BASE_GOOD_BAD_ODDS = 20.0
PDO = 20.0

FORBIDDEN_KEYWORDS = ("property", "development", "subdivision", "land banking")

INDUSTRY_SETTINGS = {
    "Agriculture, Forestry and Fishing": {
        "classification_risk_score": 3.75,
        "macro_risk_score": 3.20,
        "final_industry_risk_score": 3.09,
        "risk_level": "Elevated",
        "revenue_range": (4_000_000, 24_000_000),
        "ebitda_margin": (0.10, 0.20),
        "growth_mean": 0.05,
        "growth_std": 0.10,
    },
    "Manufacturing": {
        "classification_risk_score": 3.75,
        "macro_risk_score": 3.20,
        "final_industry_risk_score": 3.09,
        "risk_level": "Elevated",
        "revenue_range": (8_000_000, 50_000_000),
        "ebitda_margin": (0.08, 0.18),
        "growth_mean": 0.06,
        "growth_std": 0.08,
    },
    "Retail Trade": {
        "classification_risk_score": 3.25,
        "macro_risk_score": 3.20,
        "final_industry_risk_score": 2.91,
        "risk_level": "Medium",
        "revenue_range": (3_000_000, 30_000_000),
        "ebitda_margin": (0.05, 0.12),
        "growth_mean": 0.04,
        "growth_std": 0.10,
    },
    "Wholesale Trade": {
        "classification_risk_score": 3.25,
        "macro_risk_score": 3.20,
        "final_industry_risk_score": 2.91,
        "risk_level": "Medium",
        "revenue_range": (4_000_000, 35_000_000),
        "ebitda_margin": (0.05, 0.13),
        "growth_mean": 0.05,
        "growth_std": 0.09,
    },
    "Accommodation and Food Services": {
        "classification_risk_score": 2.75,
        "macro_risk_score": 2.60,
        "final_industry_risk_score": 2.56,
        "risk_level": "Medium",
        "revenue_range": (2_500_000, 18_000_000),
        "ebitda_margin": (0.07, 0.16),
        "growth_mean": 0.05,
        "growth_std": 0.11,
    },
    "Construction - Trade Services": {
        "classification_risk_score": 2.75,
        "macro_risk_score": 2.60,
        "final_industry_risk_score": 2.56,
        "risk_level": "Medium",
        "revenue_range": (5_000_000, 40_000_000),
        "ebitda_margin": (0.06, 0.14),
        "growth_mean": 0.05,
        "growth_std": 0.12,
    },
    "Health Care and Social Assistance": {
        "classification_risk_score": 1.75,
        "macro_risk_score": 2.80,
        "final_industry_risk_score": 2.27,
        "risk_level": "Medium",
        "revenue_range": (3_000_000, 28_000_000),
        "ebitda_margin": (0.12, 0.24),
        "growth_mean": 0.07,
        "growth_std": 0.07,
    },
    "Professional, Scientific and Technical Services": {
        "classification_risk_score": 2.00,
        "macro_risk_score": 2.40,
        "final_industry_risk_score": 2.24,
        "risk_level": "Medium",
        "revenue_range": (2_000_000, 25_000_000),
        "ebitda_margin": (0.15, 0.30),
        "growth_mean": 0.08,
        "growth_std": 0.07,
    },
    "Transport, Postal and Warehousing": {
        "classification_risk_score": 2.25,
        "macro_risk_score": 2.00,
        "final_industry_risk_score": 2.20,
        "risk_level": "Medium",
        "revenue_range": (4_000_000, 40_000_000),
        "ebitda_margin": (0.08, 0.16),
        "growth_mean": 0.05,
        "growth_std": 0.09,
    },
}

PRODUCT_DEFINITIONS = (
    {
        "facility_type": "Business Overdraft",
        "product_family": "Revolving Liquidity",
        "funding_type": "Funded",
        "security_type": "Unsecured / General Security Agreement",
        "loan_term_months": 12,
        "limit_multiple_low": 0.04,
        "limit_multiple_high": 0.15,
        "min_years_trading": 1,
        "min_gst_registered_years": 1,
        "min_turnover": 75_000,
        "max_turnover": 75_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 0,
        "requires_debtor_ledger": False,
        "requires_trade_docs": False,
        "clean_down_required": True,
        "product_margin_addon_pct": 0.20,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Working capital support",
            "Payroll and supplier timing gap",
            "Seasonal inventory funding",
        ),
    },
    {
        "facility_type": "Working Capital Revolver",
        "product_family": "Revolving Liquidity",
        "funding_type": "Funded",
        "security_type": "General Security Agreement",
        "loan_term_months": 24,
        "limit_multiple_low": 0.06,
        "limit_multiple_high": 0.18,
        "min_years_trading": 1,
        "min_gst_registered_years": 1,
        "min_turnover": 100_000,
        "max_turnover": 75_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 6,
        "requires_debtor_ledger": False,
        "requires_trade_docs": False,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.15,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Working capital support",
            "Trade cycle funding",
            "Short-term operating expansion",
        ),
    },
    {
        "facility_type": "Unsecured Term Loan",
        "product_family": "Term Cash Flow",
        "funding_type": "Funded",
        "security_type": "Unsecured / General Security Agreement",
        "loan_term_months": 36,
        "limit_multiple_low": 0.05,
        "limit_multiple_high": 0.20,
        "min_years_trading": 2,
        "min_gst_registered_years": 1,
        "min_turnover": 100_000,
        "max_turnover": 75_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 6,
        "requires_debtor_ledger": False,
        "requires_trade_docs": False,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.10,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Short-term operating expansion",
            "Working capital support",
            "Debtor timing bridge",
        ),
    },
    {
        "facility_type": "Trade Finance Line",
        "product_family": "Trade Finance",
        "funding_type": "Funded",
        "security_type": "General Security Agreement / Trade Assets",
        "loan_term_months": 12,
        "limit_multiple_low": 0.04,
        "limit_multiple_high": 0.12,
        "min_years_trading": 1,
        "min_gst_registered_years": 1,
        "min_turnover": 250_000,
        "max_turnover": 100_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 6,
        "requires_debtor_ledger": False,
        "requires_trade_docs": True,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.30,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Trade cycle funding",
            "Supplier payment bridge",
            "Import inventory funding",
        ),
    },
    {
        "facility_type": "Invoice Finance",
        "product_family": "Receivables Finance",
        "funding_type": "Funded",
        "security_type": "Receivables Assignment / GSA",
        "loan_term_months": 12,
        "limit_multiple_low": 0.40,
        "limit_multiple_high": 0.90,
        "min_years_trading": 1,
        "min_gst_registered_years": 1,
        "min_turnover": 250_000,
        "max_turnover": 100_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 6,
        "requires_debtor_ledger": True,
        "requires_trade_docs": False,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.35,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Debtor timing bridge",
            "Receivables funding",
            "Trade cycle funding",
        ),
    },
    {
        "facility_type": "Trade Receivables Finance",
        "product_family": "Receivables Finance",
        "funding_type": "Funded",
        "security_type": "Receivables Assignment / GSA",
        "loan_term_months": 12,
        "limit_multiple_low": 0.35,
        "limit_multiple_high": 0.80,
        "min_years_trading": 1,
        "min_gst_registered_years": 1,
        "min_turnover": 250_000,
        "max_turnover": 150_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 6,
        "requires_debtor_ledger": True,
        "requires_trade_docs": False,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.30,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Receivables funding",
            "Working capital support",
            "Trade cycle funding",
        ),
    },
    {
        "facility_type": "Business Credit Card",
        "product_family": "Business Cards",
        "funding_type": "Funded",
        "security_type": "Unsecured",
        "loan_term_months": 12,
        "limit_multiple_low": 0.01,
        "limit_multiple_high": 0.05,
        "min_years_trading": 1,
        "min_gst_registered_years": 1,
        "min_turnover": 75_000,
        "max_turnover": 25_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 0,
        "requires_debtor_ledger": False,
        "requires_trade_docs": False,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.40,
        "contingent_conversion_factor": 1.00,
        "purpose_options": (
            "Business expenses and travel",
            "Small operating purchases",
            "Staff expense management",
        ),
    },
    {
        "facility_type": "Bank Guarantee",
        "product_family": "Contingent Facilities",
        "funding_type": "Contingent",
        "security_type": "Indemnity / GSA / Cash Flow Support",
        "loan_term_months": 18,
        "limit_multiple_low": 0.02,
        "limit_multiple_high": 0.10,
        "min_years_trading": 2,
        "min_gst_registered_years": 1,
        "min_turnover": 150_000,
        "max_turnover": 150_000_000,
        "min_bank_statement_months": 6,
        "min_accounting_months": 6,
        "requires_debtor_ledger": False,
        "requires_trade_docs": True,
        "clean_down_required": False,
        "product_margin_addon_pct": 0.25,
        "contingent_conversion_factor": 0.50,
        "purpose_options": (
            "Performance guarantee support",
            "Rental or contract guarantee",
            "Trade obligation support",
        ),
    },
)

CANDIDATE_FEATURES = [
    "product_family",
    "funding_type",
    "industry_risk_score",
    "facility_type",
    "security_type",
    "years_trading",
    "gst_registered_years",
    "requested_limit_to_revenue",
    "dscr",
    "debt_to_ebitda",
    "current_ratio",
    "free_cash_flow_margin",
    "revenue_cagr_2y",
    "bureau_score",
    "commercial_defaults_24m",
    "recent_credit_inquiries_6m",
    "days_beyond_terms_avg",
    "months_negative_net_cash",
    "nsf_count_12m",
    "avg_end_balance_to_turnover",
    "clean_down_days_12m",
    "peak_limit_utilisation_pct",
    "excess_days_12m",
    "eligible_receivables_pct",
    "aged_receivables_90dpd_pct",
    "top_5_debtor_concentration_pct",
    "dilution_pct",
    "card_utilisation_avg_pct",
    "card_cash_advance_pct",
    "card_days_past_due_12m",
    "trade_cycle_days",
    "supplier_concentration_pct",
    "document_discrepancies_12m",
    "fx_exposure_pct",
    "counterparty_strength_score",
    "guarantee_tenor_months",
    "guarantee_call_event_flag",
    "eligibility_status",
    "tax_arrears_flag",
    "wc_flag",
]

SCORE_BAND_RULES = (
    {
        "band": "A",
        "max_pd": 0.025,
        "decision": "Approve",
        "review_frequency": "Annual",
        "approval_authority": "Business banker delegated authority",
        "limit_factor": 1.00,
        "pricing_margin_pct": 2.10,
        "conditions": "Standard annual review and annual financial statements.",
    },
    {
        "band": "B",
        "max_pd": 0.050,
        "decision": "Approve",
        "review_frequency": "Annual",
        "approval_authority": "Senior business banker",
        "limit_factor": 0.95,
        "pricing_margin_pct": 2.50,
        "conditions": "Annual review with bank statements and BAS/IAS refresh.",
    },
    {
        "band": "C",
        "max_pd": 0.090,
        "decision": "Refer",
        "review_frequency": "Semi-annual",
        "approval_authority": "Senior credit manager",
        "limit_factor": 0.80,
        "pricing_margin_pct": 3.10,
        "conditions": "Half-year review, covenant monitoring, statement conduct check.",
    },
    {
        "band": "D",
        "max_pd": 0.150,
        "decision": "Refer with conditions",
        "review_frequency": "Quarterly",
        "approval_authority": "Credit committee",
        "limit_factor": 0.60,
        "pricing_margin_pct": 4.00,
        "conditions": "Quarterly management accounts, tax status confirmation, tighter limit.",
    },
    {
        "band": "E",
        "max_pd": 1.000,
        "decision": "Decline",
        "review_frequency": "N/A",
        "approval_authority": "Credit committee",
        "limit_factor": 0.00,
        "pricing_margin_pct": 5.50,
        "conditions": "Outside appetite for cash flow lending under current policy.",
    },
)
